"""AWS SCP constants and limits."""

# ── AWS SCP hard limits ──────────────────────────────────────────────
# Limits updated May 2026: https://aws.amazon.com/about-aws/whats-new/2026/05/aws-organizations-increased-scp-quotas/
MAX_SCP_SIZE_BYTES: int = 10_240
MAX_STATEMENTS_PER_SCP: int = 5
MAX_SCPS_PER_TARGET: int = 10

# ── SCP JSON structure ───────────────────────────────────────────────
VALID_EFFECTS: frozenset[str] = frozenset({"Allow", "Deny"})
REQUIRED_SCP_VERSION: str = "2012-10-17"

# ── Condition operators ──────────────────────────────────────────────
CONDITION_OPERATORS: frozenset[str] = frozenset(
    {
        # String
        "StringEquals",
        "StringNotEquals",
        "StringEqualsIgnoreCase",
        "StringNotEqualsIgnoreCase",
        "StringLike",
        "StringNotLike",
        # Numeric
        "NumericEquals",
        "NumericNotEquals",
        "NumericLessThan",
        "NumericLessThanEquals",
        "NumericGreaterThan",
        "NumericGreaterThanEquals",
        # Date
        "DateEquals",
        "DateNotEquals",
        "DateLessThan",
        "DateLessThanEquals",
        "DateGreaterThan",
        "DateGreaterThanEquals",
        # Bool
        "Bool",
        # IP
        "IpAddress",
        "NotIpAddress",
        # ARN
        "ArnEquals",
        "ArnNotEquals",
        "ArnLike",
        "ArnNotLike",
        # Null check
        "Null",
        # IfExists variants (handled dynamically)
    }
)

# ── Common AWS global condition keys ─────────────────────────────────
GLOBAL_CONDITION_KEYS: frozenset[str] = frozenset(
    {
        "aws:CalledVia",
        "aws:CalledViaFirst",
        "aws:CalledViaLast",
        "aws:CurrentTime",
        "aws:EpochTime",
        "aws:FederatedProvider",
        "aws:MultiFactorAuthAge",
        "aws:MultiFactorAuthPresent",
        "aws:PrincipalAccount",
        "aws:PrincipalArn",
        "aws:PrincipalIsAWSService",
        "aws:PrincipalOrgID",
        "aws:PrincipalOrgPaths",
        "aws:PrincipalServiceName",
        "aws:PrincipalServiceNamesList",
        "aws:PrincipalTag",
        "aws:PrincipalType",
        "aws:Referer",
        "aws:RequestedRegion",
        "aws:RequestTag",
        "aws:ResourceAccount",
        "aws:ResourceOrgID",
        "aws:ResourceOrgPaths",
        "aws:ResourceTag",
        "aws:SecureTransport",
        "aws:SourceAccount",
        "aws:SourceArn",
        "aws:SourceIdentity",
        "aws:SourceIp",
        "aws:SourceVpc",
        "aws:SourceVpce",
        "aws:TagKeys",
        "aws:TokenIssueTime",
        "aws:UserAgent",
        "aws:ViaAWSService",
        "aws:VpcSourceIp",
    }
)

# ── Well-known AWS service action prefixes ───────────────────────────
# Not exhaustive — used for prefix validation, not as a complete allowlist.
SERVICE_PREFIXES: frozenset[str] = frozenset(
    {
        "access-analyzer",
        "account",
        "acm",
        "apigateway",
        "appstream",
        "athena",
        "autoscaling",
        "backup",
        "batch",
        "bedrock",
        "cloudformation",
        "cloudfront",
        "cloudhsm",
        "cloudtrail",
        "cloudwatch",
        "codebuild",
        "codecommit",
        "codedeploy",
        "codepipeline",
        "cognito-identity",
        "cognito-idp",
        "config",
        "connect",
        "datasync",
        "dax",
        "directconnect",
        "dms",
        "ds",
        "dynamodb",
        "ebs",
        "ec2",
        "ecr",
        "ecs",
        "efs",
        "eks",
        "elasticache",
        "elasticbeanstalk",
        "elasticfilesystem",
        "elasticloadbalancing",
        "elasticmapreduce",
        "emr-serverless",
        "es",
        "events",
        "firehose",
        "fsx",
        "glacier",
        "globalaccelerator",
        "glue",
        "grafana",
        "greengrass",
        "guardduty",
        "health",
        "iam",
        "imagebuilder",
        "inspector",
        "inspector2",
        "iot",
        "kafka",
        "kendra",
        "kinesis",
        "kinesisanalytics",
        "kms",
        "lakeformation",
        "lambda",
        "lex",
        "license-manager",
        "lightsail",
        "logs",
        "macie2",
        "mediaconnect",
        "mediaconvert",
        "medialive",
        "mediapackage",
        "memorydb",
        "mq",
        "neptune",
        "networkmanager",
        "opensearch",
        "opsworks",
        "organizations",
        "outposts",
        "personalize",
        "pinpoint",
        "polly",
        "qldb",
        "quicksight",
        "ram",
        "rds",
        "redshift",
        "rekognition",
        "resource-explorer-2",
        "resource-groups",
        "rolesanywhere",
        "route53",
        "route53resolver",
        "s3",
        "s3-outposts",
        "sagemaker",
        "savingsplans",
        "scheduler",
        "schemas",
        "sdb",
        "secretsmanager",
        "securityhub",
        "serverlessrepo",
        "servicecatalog",
        "servicediscovery",
        "ses",
        "shield",
        "signer",
        "sns",
        "sqs",
        "ssm",
        "sso",
        "states",
        "storagegateway",
        "sts",
        "support",
        "swf",
        "synthetics",
        "tag",
        "textract",
        "timestream",
        "transcribe",
        "transfer",
        "translate",
        "trustedadvisor",
        "waf",
        "waf-regional",
        "wafv2",
        "wellarchitected",
        "workspaces",
        "xray",
    }
)
